# Generated by Django 4.1.7 on 2023-04-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_details',
            old_name='Customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer_details',
            old_name='Customer_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='customer_details',
            old_name='Customer_username',
            new_name='username',
        ),
    ]
