# Generated by Django 4.1.7 on 2023-04-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_customer_email_customer_details_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('alt', models.CharField(max_length=20)),
                ('small_des', models.TextField()),
                ('big_des', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('s_icon', models.CharField(max_length=50)),
                ('c_icon', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
