# Generated by Django 4.1.7 on 2023-04-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='img',
            field=models.ImageField(max_length=30, upload_to=''),
        ),
    ]
