# Generated by Django 4.1.7 on 2023-04-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_product_details_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=20)),
                ('c_icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product_details',
            name='s_icon',
            field=models.IntegerField(max_length=50),
        ),
    ]
