# Generated by Django 4.1.7 on 2023-04-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_purchase_details_alter_product_details_s_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_details',
            name='category',
            field=models.CharField(default=6, max_length=50),
            preserve_default=False,
        ),
    ]
