# Generated by Django 4.1.7 on 2023-04-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_product_details_s_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('img', models.ImageField(max_length=30, upload_to='')),
                ('alt', models.CharField(max_length=20)),
                ('small_des', models.TextField()),
                ('big_des', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('s_icon', models.CharField(max_length=50)),
                ('c_icon', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='purchase_details',
        ),
    ]
