# Generated by Django 4.1.7 on 2023-04-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_store_details_delete_purchase_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=20)),
                ('f_1', models.CharField(max_length=100)),
                ('s_2', models.ImageField(upload_to='')),
                ('t_3', models.CharField(max_length=100)),
                ('f_4', models.CharField(max_length=100)),
                ('f_5', models.CharField(max_length=100)),
                ('s_6', models.CharField(max_length=100)),
                ('s_7', models.CharField(max_length=100)),
                ('l_1', models.CharField(max_length=1500)),
                ('l_2', models.ImageField(max_length=1500, upload_to='')),
                ('l_3', models.CharField(max_length=1500)),
                ('l_4', models.CharField(max_length=1500)),
                ('l_5', models.CharField(max_length=1500)),
                ('l_6', models.CharField(max_length=1500)),
                ('l_7', models.CharField(max_length=1500)),
            ],
        ),
    ]
