# Generated by Django 4.1.7 on 2023-04-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_course_page_l_2_alter_course_page_s_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=20)),
                ('q_n', models.CharField(max_length=50)),
            ],
        ),
    ]
