# Generated by Django 4.1.7 on 2023-04-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='alt',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='store_details',
            unique_together={('username', 'alt')},
        ),
    ]
