# Generated by Django 4.1.7 on 2023-04-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_customer_details_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_details',
            name='score',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
