# Generated by Django 4.1.7 on 2023-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_store_details_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_details',
            name='score',
            field=models.IntegerField(max_length=50),
        ),
    ]
