# Generated by Django 4.1.7 on 2023-04-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_store_details_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='store_details',
            name='score',
            field=models.IntegerField(),
        ),
    ]
